Repository saebyeok0306/Devlog, pull requests merged in 2024-12, with the labels that each got.

#46 feat: Apply CustomException and change JWT error status codes to 9xx
  backend/gateway-service/src/main/java/io/blog/gateway/authentication/filter/AuthenticationProcessingFilter.java
  backend/gateway-service/src/main/java/io/blog/gateway/global/response/ErrorResponse.java
  backend/gateway-service/src/main/java/io/blog/gateway/status/CustomStatus.java
  backend/main-service/src/main/java/io/blog/devlog/domain/category/service/CategoryService.java
  backend/main-service/src/main/java/io/blog/devlog/domain/comment/controller/CommentController.java
  backend/main-service/src/main/java/io/blog/devlog/domain/comment/service/CommentService.java
  backend/main-service/src/main/java/io/blog/devlog/domain/file/controller/FileController.java
  backend/main-service/src/main/java/io/blog/devlog/domain/file/handler/FileHandler.java
  backend/main-service/src/main/java/io/blog/devlog/domain/info/controller/InfoController.java
  backend/main-service/src/main/java/io/blog/devlog/domain/info/service/InfoService.java
  backend/main-service/src/main/java/io/blog/devlog/domain/like/controller/PostLikeController.java
  backend/main-service/src/main/java/io/blog/devlog/domain/post/controller/PostController.java
  backend/main-service/src/main/java/io/blog/devlog/domain/post/service/PostService.java
  backend/main-service/src/main/java/io/blog/devlog/domain/post/service/PostUploadService.java
  backend/main-service/src/main/java/io/blog/devlog/domain/user/controller/AuthController.java
  backend/main-service/src/main/java/io/blog/devlog/domain/user/model/User.java
  backend/main-service/src/main/java/io/blog/devlog/domain/user/service/UserService.java
  backend/main-service/src/main/java/io/blog/devlog/global/exception/GlobalExceptionHandler.java
  backend/main-service/src/main/java/io/blog/devlog/global/exception/InvalidJwtException.java
  backend/main-service/src/main/java/io/blog/devlog/global/exception/NoPermissionException.java
  backend/main-service/src/main/java/io/blog/devlog/global/exception/NotFoundException.java
  backend/main-service/src/main/java/io/blog/devlog/global/exception/NullJwtException.java
  backend/main-service/src/main/java/io/blog/devlog/global/exception/UnauthorizedAccessException.java
  backend/main-service/src/main/java/io/blog/devlog/global/jwt/service/JwtService.java
  backend/main-service/src/main/java/io/blog/devlog/global/login/filter/AuthenticationProcessingFilter.java
  backend/main-service/src/main/java/io/blog/devlog/global/response/ErrorResponse.java
  backend/main-service/src/main/java/io/blog/devlog/global/status/CustomStatus.java
  backend/main-service/src/test/java/io/blog/devlog/domain/comment/service/CommentServiceTest.java
  backend/main-service/src/test/java/io/blog/devlog/domain/info/service/InfoServiceTest.java
  backend/main-service/src/test/java/io/blog/devlog/domain/post/service/PostServiceTest.java
  frontend/.gitignore
  frontend/src/api/Axios.jsx
  frontend/src/api/User.jsx
  frontend/src/components/editor/postEditor/publish/Publish.jsx
  frontend/src/components/post/Post.jsx
  frontend/src/components/post/Post.scss
  frontend/src/components/post/PostInitializer.jsx
  frontend/src/containers/post/PostCommentContainer.jsx
  frontend/src/utils/authenticate.jsx
  frontend/src/utils/reactGA4.jsx
Labels: feat, fix, refactor

#49 fix: Resolve bug causing total visitor count not to update
  frontend/src/components/side/visit/Visit.jsx
Labels: fix

#51 fix: Exclude non-public posts from sitemap generation
  .github/workflows/frontend_dev_cd.yml
  .gitignore
  backend/main-service/build.gradle
  backend/main-service/src/main/java/io/blog/devlog/domain/category/model/Category.java
  backend/main-service/src/main/java/io/blog/devlog/domain/post/controller/PostController.java
  backend/main-service/src/main/java/io/blog/devlog/domain/post/service/PostService.java
  backend/main-service/src/main/java/io/blog/devlog/domain/post/service/PublicPostService.java
  backend/main-service/src/main/java/io/blog/devlog/domain/post/service/PublicPostServiceImpl.java
  backend/main-service/src/main/java/io/blog/devlog/domain/user/model/User.java
  backend/main-service/src/main/java/io/blog/devlog/global/login/filter/AuthenticationProcessingFilter.java
  backend/main-service/src/test/java/io/blog/devlog/domain/comment/service/CommentServiceTest.java
  backend/main-service/src/test/java/io/blog/devlog/domain/post/repository/PostRepositoryTest.java
  backend/main-service/src/test/java/io/blog/devlog/domain/post/service/PostServiceTest.java
  backend/main-service/src/test/java/io/blog/devlog/domain/post/service/PublicPostServiceTest.java
  backend/main-service/src/test/java/io/blog/devlog/domain/user/service/UserService2Test.java
  backend/main-service/src/test/java/io/blog/devlog/domain/user/service/UserServiceTest.java
  backend/main-service/src/test/java/io/blog/devlog/utils/EntityFactory.java
  backend/main-service/src/test/java/io/blog/devlog/utils/EntityFactoryTest.java
  frontend/src/api/Posts.jsx
  frontend/src/components/base/userLogin/signup/Signup.jsx
  frontend/src/components/category/edit/EditCategory.jsx
  frontend/src/components/editor/postEditor/PostEditor.jsx
  frontend/src/components/editor/postEditor/custom/FileUploader.jsx
  frontend/src/components/editor/postEditor/custom/TitleSuggestion.jsx
  frontend/src/components/editor/postEditor/fileUploader/FileUploader.jsx
  frontend/src/components/posts/Posts.jsx
  frontend/src/components/profile/Profile.jsx
  frontend/src/components/profile/imageCrop/ImageCrop.jsx
  frontend/src/components/side/profile/Profile.jsx
  frontend/src/components/side/toc/TOC.jsx
  frontend/src/components/side/visit/Visit.jsx
  frontend/src/pages/Callback.jsx
  frontend/src/utils/AuthProvider.jsx
  frontend/src/utils/authenticate.jsx
Labels: fix, refactor, ci/cd

#52 feat: Update sitemap on category permission changes
  backend/main-service/src/main/java/io/blog/devlog/domain/category/service/CategoryService.java
  backend/main-service/src/main/java/io/blog/devlog/domain/post/controller/PostController.java
  backend/main-service/src/main/java/io/blog/devlog/domain/post/model/Post.java
  backend/main-service/src/main/java/io/blog/devlog/domain/post/model/PostViews.java
  backend/main-service/src/main/java/io/blog/devlog/domain/post/model/PostViewsId.java
  backend/main-service/src/main/java/io/blog/devlog/domain/post/service/PostService.java
  backend/main-service/src/main/java/io/blog/devlog/domain/post/service/PostUploadService.java
  backend/main-service/src/test/java/io/blog/devlog/domain/category/service/CategoryServiceTest.java
  backend/main-service/src/test/java/io/blog/devlog/domain/post/service/PostServiceTest.java
Labels: feat, fix

#53 refactor: Change token check to use refreshToken instead of accessToken
  backend/main-service/src/main/java/io/blog/devlog/domain/user/controller/AuthController.java
  backend/main-service/src/main/java/io/blog/devlog/domain/user/service/UserService.java
  backend/main-service/src/test/java/io/blog/devlog/domain/user/service/UserService2Test.java
Labels: refactor

#55 fix: Correct typo from 'images' to 'image' in docker-compose.prod.yml
  docker-compose.prod.yml
Labels: fix

#56 ci: Build images for linux/arm64 in CI/CD
  .github/workflows/frontend_main_cd.yml
Labels: ci/cd

#57 chore: Change Docker image build to server
  .github/workflows/frontend_main_cd.yml
  docker-compose.prod.yml
Labels: ci/cd

#58 ci/cd: Update Node.js version from 16 to 18
  .github/workflows/frontend_main_cd.yml
Labels: ci/cd

#59 ci: fix frontend
  .github/workflows/frontend_main_cd.yml
Labels: ci/cd

#60 ci/cd: Add frontend deployment pipeline for self-hosted arm64
  .github/workflows/frontend_main_cd.yml
  docker-compose.yml
  frontend/.gitignore
  frontend/.vscode/settings.json
  frontend/src/api/axios.js
  frontend/src/app/post/[postUrl]/page.js
  frontend/src/utils/CredentialProvider.js
  frontend/src/utils/NextProvider.js
  frontend/src/utils/NextThemeProvider.js
  frontend/src/utils/authenticate.jsx
Labels: feat, fix, ci/cd

#62 fix: Resolve bug by resetting page on category change
  frontend/src/components/category/display/Category.jsx
  frontend/src/components/posts/Posts.jsx
  frontend/src/recoil/postPagingAtom.js
Labels: fix

#63 ci/cd: Update Docker-related code for frontend cd pipeline
  .github/workflows/frontend_main_cd.yml
Labels: ci/cd

#64 feat: Add new post notification for categories
  .github/workflows/frontend_main_cd.yml
  README.md
  backend/main-service/src/main/java/io/blog/devlog/domain/category/controller/CategoryController.java
  backend/main-service/src/main/java/io/blog/devlog/domain/category/dto/CategoryDto.java
  backend/main-service/src/main/java/io/blog/devlog/domain/category/model/Category.java
  backend/main-service/src/main/java/io/blog/devlog/domain/category/repository/CategoryRepository.java
  backend/main-service/src/main/java/io/blog/devlog/domain/category/service/CategoryService.java
  backend/main-service/src/main/java/io/blog/devlog/domain/post/controller/PostController.java
  backend/main-service/src/main/java/io/blog/devlog/domain/post/repository/PostRepository.java
  backend/main-service/src/main/java/io/blog/devlog/domain/post/service/PostService.java
  backend/main-service/src/main/java/io/blog/devlog/domain/post/service/PostUploadService.java
  backend/main-service/src/test/java/io/blog/devlog/domain/post/repository/PostRepositoryTest.java
  frontend/.env.development
  frontend/.env.production
  frontend/src/api/axios.js
  frontend/src/api/posts.js
  frontend/src/app/editor/[postUrl]/page.js
  frontend/src/app/editor/page.js
  frontend/src/app/layout.js
  frontend/src/app/login/page.js
  frontend/src/app/manager/category/page.js
  frontend/src/app/not-found.js
  frontend/src/app/post/[postUrl]/page.js
  frontend/src/app/post/[postUrl]/statistics/page.js
  frontend/src/app/profile/page.js
  frontend/src/app/signup/page.js
  frontend/src/components/category/display/Category.jsx
  frontend/src/components/category/display/Category.scss
  frontend/src/constants/api/url.js
  frontend/src/constants/base/main.js
  frontend/src/containers/post/PostCommentContainer.jsx
  frontend/src/utils/NextPostProcesser.js
  frontend/src/utils/reactGA4.jsx
Labels: feat, fix

#65 feat: Add profile card component to post footer
  backend/main-service/src/main/java/io/blog/devlog/domain/blog/model/Blog.java
  backend/main-service/src/main/java/io/blog/devlog/domain/comment/model/Comment.java
  backend/main-service/src/main/java/io/blog/devlog/domain/like/model/PostLike.java
  backend/main-service/src/main/java/io/blog/devlog/domain/post/model/Post.java
  backend/main-service/src/main/java/io/blog/devlog/domain/user/controller/ProfileController.java
  backend/main-service/src/main/java/io/blog/devlog/domain/user/dto/RequestProfileDto.java
  backend/main-service/src/main/java/io/blog/devlog/domain/user/dto/ResponseUserDto.java
  backend/main-service/src/main/java/io/blog/devlog/domain/user/dto/ResponseUserProfileDto.java
  backend/main-service/src/main/java/io/blog/devlog/domain/user/model/User.java
  frontend/public/robots.txt
  frontend/src/api/user.js
  frontend/src/components/base/comment/Comment.jsx
  frontend/src/components/base/comment/comments/Comments.jsx
  frontend/src/components/base/comment/comments/CommentsHandler.jsx
  frontend/src/components/editor/postEditor/PostEditor.jsx
  frontend/src/components/editor/postEditor/fileUploader/FileUploader.jsx
  frontend/src/components/post/Post.jsx
  frontend/src/components/profile/Profile.jsx
  frontend/src/components/profile/Profile.scss
  frontend/src/components/profile/imageCrop/ImageCrop.jsx
  frontend/src/components/profile/profileItem/info/Info.jsx
  frontend/src/components/profile/profileItem/info/Info.scss
  frontend/src/components/side/profile/Profile.jsx
  frontend/src/components/tailcard/Tailcard.jsx
  frontend/src/components/tailcard/Tailcard.scss
  frontend/src/components/tailcard/index.js
  frontend/src/containers/editor/PostEditorContainer.jsx
  frontend/src/containers/post/PostCommentContainer.jsx
  frontend/src/recoil/authAtom.js
  frontend/src/recoil/blogAtom.js
  frontend/src/recoil/commentAtom.js
  frontend/src/recoil/editorAtom.js
  frontend/src/recoil/postAtom.js
  frontend/src/utils/CredentialProvider.js
  frontend/src/utils/ImageResizer.jsx
  frontend/src/utils/NextThemeProvider.js
  frontend/src/utils/authenticate.jsx
Labels: feat, fix

#66 feat: Add layout.js for page access control
  frontend/src/app/editor/layout.js
  frontend/src/app/login/layout.js
  frontend/src/app/manager/layout.js
  frontend/src/app/profile/layout.js
  frontend/src/app/signup/layout.js
Labels: feat

#67 fix: Resolve visitor count aggregation bug
  frontend/src/utils/NextThemeProvider.js
Labels: fix
